### ISSUE TITLE
Can you please include Haitian Creole [ht] and Hmong Daw (Latin) mww to Multilingual App Toolkit?

### ISSUE THREAD

**Issue by pooranoayaw** [microsoft/Multilingual-App-Toolkit#9]
Please add these two languages Haitian Creole [ht] and Hmong Daw (Latin) [mww] to MAT? They are available in Cognitive Services https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support.

Meanwhile, can you tell us how to go about adding these languages manually?

**Comment by pooran** [comment]
@joshftb @RogerSmithR @JPTGamesAndApps ?

**Comment by joshftb** [comment]
Hi @pooranoayaw, currently there is no way to add those languages manually. We'll create the work item to get those added.

**Comment by pooranoayaw** [comment]
Thanks for the update, will look forward to using it soon.

**Comment by pooranoayaw** [comment]
What is the alternative in our current project  that we can follow to add these languages and get the translations from Azure?

**Comment by pooranoayaw** [comment]
> Hi @pooranoayaw, currently there is no way to add those languages manually. We'll create the work item to get those added.

Any ETA for this?

**Comment by joshftb** [comment]
> > Hi @pooranoayaw, currently there is no way to add those languages manually. We'll create the work item to get those added.
> 
> Any ETA for this?

We will add them by July 22

**Comment by joshftb** [comment]
Hi,

We will not be able to add these languages because it will result in a system-wide configuration change. More specifically, we would have to install those languages locally, and they would become available to all applications. This is due to a limitation of the System.Globalization namespace, which only allows new cultures to be added globally. 

As a workaround, you can register this culture yourself by following this [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureandregioninfobuilder.register?view=netframework-4.8).

As long as the culturename matches what Microsoft Translator has, it will appear in the list of languages when adding a new one.
![image](https://user-images.githubusercontent.com/90873829/180321662-36b19699-d6f6-4409-853c-a7b7c2b74368.png)
